import esbuild from 'esbuild';
import process from 'node:process';

const production = process.argv[2] === 'production';

const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
*/`;

const context = await esbuild.context({
	banner: {
		js: banner,
	},
	bundle: true,
	entryPoints: ['src/main.ts'],
	external: [
		'@codemirror/autocomplete',
		'@codemirror/collab',
		'@codemirror/commands',
		'@codemirror/language',
		'@codemirror/lint',
		'@codemirror/search',
		'@codemirror/state',
		'@codemirror/view',
		'@lezer/common',
		'@lezer/highlight',
		'@lezer/lr',
		'electron',
		'obsidian',
	],
	format: 'cjs',
	loader: {
		'.svg': 'text',
	},
	logLevel: 'info',
	minify: production,
	outfile: 'main.js',
	platform: 'browser',
	sourcemap: production ? false : 'inline',
	target: 'es2018',
	treeShaking: true,
});

await context.rebuild();
await context.dispose();
