import esbuild from 'esbuild';
import process from 'node:process';

const mode = process.argv[2];
const production = mode === 'production';
const test = mode === 'test';

const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
*/`;

const context = await esbuild.context({
	banner: {
		js: banner,
	},
	bundle: true,
	entryPoints: test ? ['src/workout-entry.ts'] : ['src/main.ts'],
	external: [
		'@codemirror/autocomplete',
		'@codemirror/collab',
		'@codemirror/commands',
		'@codemirror/language',
		'@codemirror/lint',
		'@codemirror/search',
		'@codemirror/state',
		'@codemirror/view',
		'@lezer/common',
		'@lezer/highlight',
		'@lezer/lr',
		'electron',
		'obsidian',
	],
	format: test ? 'esm' : 'cjs',
	loader: {
		'.svg': 'text',
	},
	logLevel: 'info',
	minify: production,
	outfile: test ? 'node_modules/.cache/fitness-record-tests/workout-entry.js' : 'main.js',
	platform: test ? 'node' : 'browser',
	sourcemap: production ? false : 'inline',
	target: 'es2018',
	treeShaking: true,
});

await context.rebuild();
await context.dispose();
